// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from 'react';
import { AgGridReact } from 'ag-grid-react';
import { ColDef } from 'ag-grid-community';
import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-alpine.css';
import { ModuleRegistry, AllCommunityModule } from 'ag-grid-community';
ModuleRegistry.registerModules([ AllCommunityModule ]);

// Define the interface for table props
export interface AgGridTableProps {
  columnDefs: ColDef[];
  rowData: any[];
  className?: string;
  height?: string | number;
  width?: string | number;
  onRowClicked?: (event :any) => void;
  pagination?: boolean;
//   paginationPageSizeSelector?:boolean;
}

// Reusable AG Grid Table Component
export const AgGridTable: React.FC<AgGridTableProps>=({
  columnDefs,
  rowData,
  className = '',
  height = 500,
  width = '100%',
  ...rest
})=> {
  return (
    <div
      className={`ag-theme-alpine ${className}`}
      style={{ height, width }}
    >
      <AgGridReact
        rowData={rowData}
        columnDefs={columnDefs}
        domLayout="autoHeight"
        {...rest}
      />
    </div>
  );
}
